### ISSUE TITLE
Installation via `pipx` fails now that the console script is gone

### ISSUE THREAD

**Issue by dreuter** [scivision/findssh#5]
Hey scivision,

First of all thanks for this really great project. Especially its ease of use compared to `nmap` and the fact that it directly outputs all and only the information that I need is really great (outputting the `ssh` version is genius, as I was able to find the robots (physical robots) versus all developer PCs at my last employer with ease by looking at the `ssh` version). You saved me so much time already!

I do have one question/feature request though :) In the commit fb953cfa210ca3bfb4cf36160076d16b5ef83933 you have deleted the console script. Is there any reason why? I liked the briefness of `findssh` as I used the command quite a lot

But even more importantly I always installed `findssh` via [`pipx`](https://pypa.github.io/pipx/) (another awesome tool BTW, it lets you install cli tools without ever running into version conflicts and in a very clean way), but this is no longer possible, because it requires a console script. Of course I can simply install version `1.5.0` and this version works fine as well, but I would rather get the latest and greatest ;)

**Comment by scivision** [comment]
Thanks this is fixed in v2.0.1, it was an oversight when upgrading from setup.cfg to pyproject.toml
